test_that("Non-parametric Bootstrap mean result consistency", {
  set.seed(67)
  X <- rnorm(1000)
  set.seed(67)
  obj1 <- bootstrap(X, B = 1000, dist = "NonParam", conf_level = 0.95)
  set.seed(67)
  obj2 <- bootstrap_cpp_integrated(X, B = 1000, dist = "NonParam", conf_level = 0.95)
  set.seed(67)
  obj3 <- bootstrap_par_cpp(X, B = 1000, dist = "NonParam", cores = 2, conf_level = 0.95)
  expect_equal(mean(obj1$bootstrap_means), mean(obj2$bootstrap_means), tolerance = 0.01)
  expect_equal(mean(obj1$bootstrap_means), mean(obj3$bootstrap_means), tolerance = 0.01)
})

test_that("Non-parametric Bootstrap sd result consistency", {
  set.seed(67)
  X <- rnorm(1000)
  set.seed(67)
  obj1 <- bootstrap(X, B = 1000, dist = "NonParam", conf_level = 0.95)
  set.seed(67)
  obj2 <- bootstrap_cpp_integrated(X, B = 1000, dist = "NonParam", conf_level = 0.95)
  set.seed(67)
  obj3 <- bootstrap_par_cpp(X, B = 1000, dist = "NonParam", cores = 2, conf_level = 0.95)
  expect_equal(mean(obj1$bootstrap_sds), mean(obj2$bootstrap_sds), tolerance = 0.01)
  expect_equal(mean(obj1$bootstrap_sds), mean(obj3$bootstrap_sds), tolerance = 0.01)
})
