# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap_cpp <- function(X, B, dist, param1 = NA_real_, param2 = NA_real_) {
    .Call(`_FinalProject_bootstrap_cpp`, X, B, dist, param1, param2)
}

